/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Farhan
 */
public class vRating extends javax.swing.JFrame {

    private Object getlStar1;

    /**
     * Creates new form vRating
     */
    public vRating() {
        initComponents();
        this.setLocationRelativeTo(null);
        //setSize(360, 640);
    }
    
    public JLabel getlStar1() {
        return lStar1;
    }
    
    public JLabel getlStar2() {
        return lStar2;
    }
    
    public JLabel getlStar3() {
        return lStar3;
    }
    
    public JLabel getlStar4() {
        return lStar4;
    }
    
    public JLabel getlStar5() {
        return lStar5;
    }
    
    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lSelesai = new javax.swing.JLabel();
        lFotoMontir = new javax.swing.JLabel();
        lNamaMontir = new javax.swing.JLabel();
        lBeriRating = new javax.swing.JLabel();
        lFeedback = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taFeedback = new javax.swing.JTextArea();
        bSubmit = new javax.swing.JButton();
        lStar1 = new javax.swing.JLabel();
        lStar2 = new javax.swing.JLabel();
        lStar3 = new javax.swing.JLabel();
        lStar4 = new javax.swing.JLabel();
        lStar5 = new javax.swing.JLabel();
        lKetStar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 102, 0));

        lSelesai.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        lSelesai.setForeground(new java.awt.Color(153, 153, 153));
        lSelesai.setText("SELESAI! :)");

        lFotoMontir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/montir.png"))); // NOI18N

        lNamaMontir.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        lNamaMontir.setForeground(new java.awt.Color(153, 153, 153));
        lNamaMontir.setText("ANHAR ABIMANYU");

        lBeriRating.setFont(new java.awt.Font("Hobo Std", 0, 13)); // NOI18N
        lBeriRating.setForeground(new java.awt.Color(153, 153, 153));
        lBeriRating.setText("BERI RATINGNYA YA");

        lFeedback.setFont(new java.awt.Font("Hobo Std", 0, 13)); // NOI18N
        lFeedback.setForeground(new java.awt.Color(153, 153, 153));
        lFeedback.setText("BERI MASUKAN");

        taFeedback.setColumns(20);
        taFeedback.setRows(5);
        jScrollPane1.setViewportView(taFeedback);

        bSubmit.setFont(new java.awt.Font("Silom", 0, 13)); // NOI18N
        bSubmit.setText("SUBMIT");
        bSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitActionPerformed(evt);
            }
        });

        lStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/brating.png"))); // NOI18N
        lStar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lStar1MouseClicked(evt);
            }
        });

        lStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/brating.png"))); // NOI18N
        lStar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lStar2MouseClicked(evt);
            }
        });

        lStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/brating.png"))); // NOI18N
        lStar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lStar3MouseClicked(evt);
            }
        });

        lStar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/brating.png"))); // NOI18N
        lStar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lStar4MouseClicked(evt);
            }
        });

        lStar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/brating.png"))); // NOI18N
        lStar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lStar5MouseClicked(evt);
            }
        });

        lKetStar.setFont(new java.awt.Font("Hobo Std", 0, 13)); // NOI18N
        lKetStar.setForeground(new java.awt.Color(150, 150, 150));
        lKetStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lKetStar.setText(" ");
        lKetStar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lSelesai))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lNamaMontir)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lStar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lStar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lStar3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lStar4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lStar5))
                            .addComponent(lKetStar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lFeedback)
                        .addGap(132, 132, 132))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(bSubmit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lBeriRating)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lFotoMontir)
                .addGap(145, 145, 145))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lSelesai)
                .addGap(18, 18, 18)
                .addComponent(lFotoMontir)
                .addGap(24, 24, 24)
                .addComponent(lNamaMontir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lBeriRating)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lStar1)
                    .addComponent(lStar2)
                    .addComponent(lStar3)
                    .addComponent(lStar5)
                    .addComponent(lStar4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lKetStar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(lFeedback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(bSubmit)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitActionPerformed

        this.showMessage("Berhasil Submit","Success", 1);
    
        vMenu men = new vMenu();
        men.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bSubmitActionPerformed

    private void lStar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lStar1MouseClicked
        // TODO add your handling code here:
        Object source = evt.getSource();
        if(source.equals(this.getlStar1())){
            this.getlStar1().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/yrating.png")));
            this.getlStar2().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/brating.png")));
            this.getlStar3().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/brating.png")));
            this.getlStar4().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/brating.png")));
            this.getlStar5().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/brating.png")));
            this.lKetStar.setText("SANGAT BURUK");
        }
    }//GEN-LAST:event_lStar1MouseClicked

    private void lStar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lStar2MouseClicked
        // TODO add your handling code here:
        Object source = evt.getSource();
        if(source.equals(this.getlStar2())){
            this.getlStar1().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/yrating.png")));
            this.getlStar2().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/yrating.png")));
            this.getlStar3().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/brating.png")));
            this.getlStar4().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/brating.png")));
            this.getlStar5().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/brating.png")));
            this.lKetStar.setText("BURUK");
        }
    }//GEN-LAST:event_lStar2MouseClicked

    private void lStar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lStar3MouseClicked
        // TODO add your handling code here:
        Object source = evt.getSource();
        if(source.equals(this.getlStar3())){
            this.getlStar1().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/yrating.png")));
            this.getlStar2().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/yrating.png")));
            this.getlStar3().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/yrating.png")));
            this.getlStar4().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/brating.png")));
            this.getlStar5().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/brating.png")));
            this.lKetStar.setText("CUKUP");
        }
    }//GEN-LAST:event_lStar3MouseClicked

    private void lStar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lStar4MouseClicked
        // TODO add your handling code here:
        Object source = evt.getSource();
        if(source.equals(this.getlStar4())){
            this.getlStar1().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/yrating.png")));
            this.getlStar2().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/yrating.png")));
            this.getlStar3().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/yrating.png")));
            this.getlStar4().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/yrating.png")));
            this.getlStar5().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/brating.png")));
            this.lKetStar.setText("BAIK");
        }
    }//GEN-LAST:event_lStar4MouseClicked

    private void lStar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lStar5MouseClicked
        // TODO add your handling code here:
        Object source = evt.getSource();
        if(source.equals(this.getlStar5())){
            this.getlStar1().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/yrating.png")));
            this.getlStar2().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/yrating.png")));
            this.getlStar3().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/yrating.png")));
            this.getlStar4().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/yrating.png")));
            this.getlStar5().setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/yrating.png")));
            this.lKetStar.setText("SANGAT BAIK");
        }
    }//GEN-LAST:event_lStar5MouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSubmit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lBeriRating;
    private javax.swing.JLabel lFeedback;
    private javax.swing.JLabel lFotoMontir;
    private javax.swing.JLabel lKetStar;
    private javax.swing.JLabel lNamaMontir;
    private javax.swing.JLabel lSelesai;
    private javax.swing.JLabel lStar1;
    private javax.swing.JLabel lStar2;
    private javax.swing.JLabel lStar3;
    private javax.swing.JLabel lStar4;
    private javax.swing.JLabel lStar5;
    private javax.swing.JTextArea taFeedback;
    // End of variables declaration//GEN-END:variables
}
