/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Farhan
 */
public class vOTW extends javax.swing.JFrame {

    /**
     * Creates new form vRating
     */
    public vOTW() {
        initComponents();
        this.setLocationRelativeTo(null);
        //setSize(360, 640);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lMaps = new javax.swing.JLabel();
        lMontir = new javax.swing.JLabel();
        lNamaMontir = new javax.swing.JLabel();
        lIDMontir = new javax.swing.JLabel();
        lRating = new javax.swing.JLabel();
        lAngkaRating = new javax.swing.JLabel();
        lTujuan = new javax.swing.JLabel();
        lCapWaktuTiba = new javax.swing.JLabel();
        lJarakMontir = new javax.swing.JLabel();
        lHarga = new javax.swing.JLabel();
        bBatal = new javax.swing.JButton();
        bMainMenu = new javax.swing.JButton();
        bSelesai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 102, 0));

        lMaps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/maps.png"))); // NOI18N

        lMontir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/montir.png"))); // NOI18N

        lNamaMontir.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        lNamaMontir.setForeground(new java.awt.Color(153, 153, 153));
        lNamaMontir.setText("ANHAR ABIMANYU");

        lIDMontir.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        lIDMontir.setForeground(new java.awt.Color(153, 153, 153));
        lIDMontir.setText("MO-001");

        lRating.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        lRating.setForeground(new java.awt.Color(153, 153, 153));
        lRating.setText("RATING");

        lAngkaRating.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        lAngkaRating.setForeground(new java.awt.Color(153, 153, 153));
        lAngkaRating.setText("4.5 / 5.0");

        lTujuan.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        lTujuan.setForeground(new java.awt.Color(153, 153, 153));
        lTujuan.setText("TO KUTABUMI");

        lCapWaktuTiba.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        lCapWaktuTiba.setForeground(new java.awt.Color(153, 153, 153));
        lCapWaktuTiba.setText("MONTIR AKAN TIBA DALAM 4 MENIT");

        lJarakMontir.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        lJarakMontir.setForeground(new java.awt.Color(153, 153, 153));
        lJarakMontir.setText("JARAK MONTIR 6 KM");

        lHarga.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        lHarga.setForeground(new java.awt.Color(153, 153, 153));
        lHarga.setText("RP 200.000 - 400.000");

        bBatal.setFont(new java.awt.Font("Silom", 0, 13)); // NOI18N
        bBatal.setText("BATAL");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        bMainMenu.setFont(new java.awt.Font("Silom", 0, 13)); // NOI18N
        bMainMenu.setText("MAIN MENU");
        bMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMainMenuActionPerformed(evt);
            }
        });

        bSelesai.setFont(new java.awt.Font("Silom", 0, 13)); // NOI18N
        bSelesai.setText("SELESAI");
        bSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSelesaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lMontir)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lIDMontir)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(lRating)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lAngkaRating))
                                                .addComponent(lNamaMontir, javax.swing.GroupLayout.Alignment.LEADING))))
                                    .addComponent(lTujuan)
                                    .addComponent(lJarakMontir)
                                    .addComponent(lCapWaktuTiba)
                                    .addComponent(lHarga)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lMaps, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(bMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(bSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lMaps, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lNamaMontir)
                        .addGap(18, 18, 18)
                        .addComponent(lIDMontir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lRating)
                            .addComponent(lAngkaRating)))
                    .addComponent(lMontir))
                .addGap(18, 18, 18)
                .addComponent(lTujuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lCapWaktuTiba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lJarakMontir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lHarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSelesai)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bBatal)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMainMenuActionPerformed
        vMenu men = new vMenu();
        men.pesan = true;
        men.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bMainMenuActionPerformed

    private void bSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSelesaiActionPerformed
        vRating selesai = new vRating();
        selesai.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bSelesaiActionPerformed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        vMenu men = new vMenu();
        men.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bMainMenu;
    private javax.swing.JButton bSelesai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lAngkaRating;
    private javax.swing.JLabel lCapWaktuTiba;
    private javax.swing.JLabel lHarga;
    private javax.swing.JLabel lIDMontir;
    private javax.swing.JLabel lJarakMontir;
    private javax.swing.JLabel lMaps;
    private javax.swing.JLabel lMontir;
    private javax.swing.JLabel lNamaMontir;
    private javax.swing.JLabel lRating;
    private javax.swing.JLabel lTujuan;
    // End of variables declaration//GEN-END:variables
}
